FROM python:3.9-slim

COPY ./streamlit_ui ./ui

WORKDIR /ui

RUN pip install --no-cache -r requirements.txt

EXPOSE 8501

ENTRYPOINT [ "python","-m","streamlit","run","Library.py" ,"--server.port=8501", "--server.address=0.0.0.0"]

